from typing import Protocol, Optional, List, Tuple, runtime_checkable


@runtime_checkable
class ISFTPConnection(Protocol):
    """SFTP 文件操作抽象接口 — 解耦 UI 层与 SSH 实现细节"""

    def is_file(self, path: str) -> bool: ...
    def chdir(self, path: str) -> None: ...
    def getcwd(self) -> str: ...
    def read_file(self, path: str) -> str: ...
    def save_file(self, path: str, text: str) -> None: ...
    def realpath(self, path: str) -> str: ...
    def del_file(self, path: str) -> None: ...
    def makedirs(self, path: str) -> None: ...
    def copy_file(self, old_path: str, new_path: str) -> None: ...
    def move_file(self, old_path: str, new_path: str) -> None: ...
    def rename(self, old_name: str, new_name: str) -> None: ...
    def get_file_size(self, path: str) -> int: ...
    def get_permissions(self, path: str) -> int: ...
    def chmod(self, path: str, permissions: int) -> None: ...
    @property
    def sftp(self) -> object: ...
    @property
    def connection(self) -> object: ...


@runtime_checkable
class ITransport(Protocol):
    """传输任务抽象接口"""

    progress_updated: object  # Signal(int)
    range_initialized: object  # Signal(int)
    transport_failed: object  # Signal(str)
    transport_cancelled: object  # Signal()
    speed_updated: object  # Signal(str)

    def start(self) -> None: ...
    def cancel(self) -> None: ...
    def toggle_pause(self) -> None: ...
    def is_cancelled(self) -> bool: ...


@runtime_checkable
class IDatabase(Protocol):
    """凭证数据库抽象接口"""

    def query_password(self, host: str, port: int, username: str, password: str) -> List[Tuple]: ...
    def insert_password(self, host: str, port: int, username: str, password: str) -> None: ...
    def query_all_password(self) -> List[Tuple]: ...
    def update_password(self, idx: int, host: str, port: int, username: str, password: str) -> None: ...
    def del_idx_password(self, idx: int) -> None: ...
    def query_key(self, host: str, port: int, username: str, key_path: str, passphrase: str = "") -> List[Tuple]: ...
    def insert_key(self, host: str, port: int, username: str, key_path: str, passphrase: str = "") -> None: ...
    def query_all_key(self) -> List[Tuple]: ...
    def update_key(self, idx: int, host: str, port: int, username: str, key_path: str, passphrase: str = "") -> None: ...
    def del_idx_key(self, idx: int) -> None: ...
    def close(self) -> None: ...
